version: '3.7'

services:
  database:
    image: postgres:13
    container_name: bchain-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bchain
      POSTGRES_USER: abdias
      POSTGRES_PASSWORD: lizzie
    ports:
      - '5432:5432'
    volumes:
      - 'pg_db:/var/lib/postgresql'

volumes:
  pg_db:
    driver: "local"
